name: main release
on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_REPOSITORY: bitbd83/roninchain
  DOCKER_FILE: Dockerfile
jobs:
  push_to_docker_registry:
    name: Push Docker image to GHCR.IO
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 'Checkout Repo'
        run: |
          git clone https://github.com/${{ github.repository }}.git .
          git checkout ${{ github.sha }}

      - name: Log in to the Container registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.repository_owner }} --password-stdin

      # Enable Registry Cache
      - name: "Set up Docker Buildx"
        run: |
          docker buildx create --name mybuilder --use --bootstrap
          docker buildx inspect

      - name: Build and push Docker image
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          docker buildx build \
            --file ${{ env.DOCKER_FILE }} \
            --platform linux/amd64,linux/arm64 \
            --tag ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}:nightly \
            --tag ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}:nightly-${SHORT_SHA} \
            --label "org.opencontainers.image.created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
            --label "org.opencontainers.image.source=https://github.com/${{ github.repository }}" \
            --label "org.opencontainers.image.revision=${{ github.sha }}" \
            --push \
            .
